### ISSUE TITLE
File "/home/gussand/github/mentat/mentat/app.py", line 117

### ISSUE THREAD

**Issue by GusSand** [biobootloader/mentat#10]
Hi:
Great demos, but when I installed from github and tried to run my local copy I always get this error. I created it's own virtual environment and all.  Any ideas? 
Thank you so much! Very excited to try it. 

[1] % mentat .
Traceback (most recent call last):
  File "/home/gussand/.venv/bin/mentat", line 5, in <module>
    from mentat.app import run_cli
  File "/home/gussand/github/mentat/mentat/app.py", line 117
    match user_response.lower():
          ^
SyntaxError: invalid syntax

**Comment by PCSwingle** [comment]
You're using a version of python before python 3.10 (where match statement was added). Try updating your python version and it should work!

**Comment by GusSand** [comment]
Thanks for the quick response. That's what I thought initially, but:

[0] % python --version
Python 3.9.12

**Comment by GusSand** [comment]
So it seems that match is *only* supported in 3.1. So I will have to change to using if else... :( 
And also in code_change.py

**Comment by PCSwingle** [comment]
Python 3.10 is the version after 3.9; version numbers aren't decimals (no matter what they look like, haha), so version 3.10 != version 3.1. I would recommend just updating python to 3.10, since there might be other features from 3.10 that we use.
