### ISSUE TITLE
ability to ignore files/folders?

### ISSUE THREAD

**Issue by gileneusz** [biobootloader/mentat#20]
Does it have an ability to ignore files or folders? For example I've got a large project with node modules or other files that I would like to exclude from the context? Or I would like to work only on particular files?

**Comment by gileneusz** [comment]
Thanks for your response @jromerooo2. While the proposed workaround could indeed work for certain use cases, I believe it might not be as efficient in a more complex scenario. For instance, let's consider a Laravel project which might have a multitude of files and directories. Manually adding each file or directory can be a tedious process and prone to errors.

I believe it would be more convenient to have a feature that allows us to exclude certain directories or files, like node_modules, public files, images, etc. This way, we can ensure that the software is able to focus on and work with the rest of the files, thus streamlining the process and increasing efficiency. It would be very beneficial to have a functionality which can easily handle such exclusions.

**Comment by biobootloader** [comment]
Hey @gileneusz , @jromerooo2 ! 

There's a PR for this: https://github.com/biobootloader/mentat/pull/8

For now it'll be in your mentat config, which is in `~/.mentat/`. Over the weekend @PCSwingle will be adding the ability to make project-specific configs for things like this!

**Comment by gileneusz** [comment]
I appreciate your feedback @jromerooo2 and @biobootloader. Here's a proposal for the functionality: why not leverage the already existing .gitignore files in most projects? These files, by default, list directories and files that we usually want to ignore, and it aligns perfectly with our requirement.

For instance, the .gitignore file in my Laravel project already excludes files and directories like node_modules, public files, images, etc. Here is what it looks like:

```
/.phpunit.cache
/node_modules
/public/hot
/public/storage
/storage/*.key
/vendor
.env
.env.backup
.env.production
.phpunit.result.cache
Homestead.json
Homestead.yaml
auth.json
npm-debug.log
yarn-error.log
/.fleet
/.idea
/.vscode
```
This could be an immediate and efficient solution for testing the functionality now. Of course, in the longer term, we could also add the ability to create a separate .mentat-ignore file for more customizability and control. But starting with .gitignore can be a straightforward and time-saving step.

**Comment by PCSwingle** [comment]
Hey @gileneusz! We already do exclude all gitignore files! Let us know if you have been having any problems with it, but it's been working for us so far.

**Comment by gileneusz** [comment]
ok, I'm make some testing during this weekend!
