### ISSUE TITLE
Windows file paths

### ISSUE THREAD

**Issue by sam1am** [biobootloader/mentat#31]
<img width="733" alt="image" src="https://github.com/biobootloader/mentat/assets/127555/152d2255-772b-4726-978d-003b72761953">

Tried it in Windows but it mixed up the file path slashes.

**Comment by biobootloader** [comment]
ah, the system is combining windows path format with the output of GPT-4, which was using unix format. Will fix asap!

**Comment by PCSwingle** [comment]
#41 fixes this! :partying_face:

**Comment by biobootloader** [comment]
@sam1am #41 is merged, it should work for you now!
