### ISSUE TITLE
How do I change the OpenAI model?

### ISSUE THREAD

**Issue by PatzEdi** [biobootloader/mentat#43]
Hello! I love this project and it is honestly really useful. But the cost is a lot when using GPT-4. Is there a way to manually change the model from GPT-4 to GPT-3.5 turbo? I thought I had seen an issue about this before but I do not see it anymore (I did not see it in the closed issues as well). There might be a way to do this already, and if there is I have not found how to do so yet and am sorry. 

Regarding the project, it is yet another example of what great things can be created when great developers and AI work together. Thanks for creating it!

**Comment by PCSwingle** [comment]
Thank you so much! There currently is not a way to change the model to 3.5; reason being that 3.5 really isn't very good at this, haha. If you really want to try it, it's super easy to switch; just a one line change on line 45 in llm_api.py. I made a quick branch for you (branch gpt-3.5-turbo) that makes the change for you, if you want to pull it down and try it. It's just a quick hack though, so the costs and a few other things won't be accurate.

**Comment by PatzEdi** [comment]
> Thank you so much! There currently is not a way to change the model to 3.5; reason being that 3.5 really isn't very good at this, haha. If you really want to try it, it's super easy to switch; just a one line change on line 45 in llm_api.py. I made a quick branch for you (branch gpt-3.5-turbo) that makes the change for you, if you want to pull it down and try it. It's just a quick hack though, so the costs and a few other things won't be accurate.

I am so sorry for this late reply! Thank you so much for the information. Yeah, I imagined it would have been a performance/capability issue when not using GPT-4. Thank you for the support, and keep it up, I am loving mentat :)
