### ISSUE TITLE
Cost estimation to run `mentat`

### ISSUE THREAD

**Issue by gaborvecsei** [biobootloader/mentat#55]
Hi, nice work!

I just wanted to ask you if you have any cost estimations for the usage of the tool. It would be really nice to see some numbers on what can we expect.

**Comment by dahifi** [comment]
It's pennies. It gives you a token usage when you exit, and it's been around a dime each time I use it, but that's with about 4-5k tokens per interaction. I'm loading my whole repo into it but you can limit it to certain files or subdirs.

**Comment by PCSwingle** [comment]
Yep, like @dahifi said it will give you a cost estimation each time you use it and it's around 4-20 pennies depending on how many files you give it.
