### ISSUE TITLE
The model `gpt-4-0314` does not exist

### ISSUE THREAD

**Issue by chadwhitacre** [biobootloader/mentat#6]
I'm getting this error and it seems I'm [not alone](https://twitter.com/bio_bootloader/status/1684303542880985088).

> The model `gpt-4-0314` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

**Comment by biobootloader** [comment]
Do you have access to `gpt-4-0613` and `gpt-4`, just not `gpt-4-0314`? You can check by first running:

`export OPENAI_API_KEY='yourkey'`

and then the following python:

```
import os
import openai

openai.api_key=os.getenv("OPENAI_API_KEY")
available_models = [x["id"] for x in openai.Model.list()["data"]]
print(sorted(available_models))
```

If you don't have any `gpt-4` access, then it should be coming soon:

<img width="670" alt="image" src="https://github.com/biobootloader/mentat/assets/128252497/4f343d1c-021d-49a6-b90b-9baaf5034e56">

If you are just missing `gpt-4-0314` then, then hopefully OpenAI will see my tweet and we can figure out why some people don't have access to that model...

**Comment by chadwhitacre** [comment]
No, I do not. Fwiw, it looks like the https://platform.openai.com/account/rate-limits page is also filtered to what's available on one's account. The end of July is so far away! 😏

```
ada
ada-code-search-code
ada-code-search-text
ada-search-document
ada-search-query
ada-similarity
babbage
babbage-code-search-code
babbage-code-search-text
babbage-search-document
babbage-search-query
babbage-similarity
code-davinci-edit-001
code-search-ada-code-001
code-search-ada-text-001
code-search-babbage-code-001
code-search-babbage-text-001
curie
curie-instruct-beta
curie-search-document
curie-search-query
curie-similarity
davinci
davinci-instruct-beta
davinci-search-document
davinci-search-query
davinci-similarity
gpt-3.5-turbo
gpt-3.5-turbo-0301
gpt-3.5-turbo-0613
gpt-3.5-turbo-16k
gpt-3.5-turbo-16k-0613
text-ada-001
text-babbage-001
text-curie-001
text-davinci-001
text-davinci-002
text-davinci-003
text-davinci-edit-001
text-embedding-ada-002
text-search-ada-doc-001
text-search-ada-query-001
text-search-babbage-doc-001
text-search-babbage-query-001
text-search-curie-doc-001
text-search-curie-query-001
text-search-davinci-doc-001
text-search-davinci-query-001
text-similarity-ada-001
text-similarity-babbage-001
text-similarity-curie-001
text-similarity-davinci-001
whisper-1
```

```
--- models-from-api     2023-07-26 17:59:21
+++ models-from-ui      2023-07-26 17:58:57
@@ -1,3 +1,4 @@
+DALL·E
 ada
 ada-code-search-code
 ada-code-search-text
@@ -38,6 +39,8 @@
 text-davinci-003
 text-davinci-edit-001
 text-embedding-ada-002
+text-moderation-latest
+text-moderation-stable
 text-search-ada-doc-001
 text-search-ada-query-001
 text-search-babbage-doc-001
```

**Comment by biobootloader** [comment]
Hopefully OpenAI grants access to everyone soon! 

For now I've made it check at startup for access and tell the user: https://github.com/biobootloader/mentat/blob/2851d699cb14dea54ef97ef7dcef2ee47d8a32ad/mentat/llm_api.py#L80
