### ISSUE TITLE
Add autocomplete for file, class, and function names

### ISSUE THREAD

**Issue by biobootloader** [biobootloader/mentat#78]
Using ctags (#66 ) to get relevant names, autocomplete them as the user types. Right now we have autocomplete for prompt history, but that's just for the entire request the user types, not on the word level. I'm not sure what switching that will look like.

This will probably have some conflicts with #59 , since that also changes user input. Might be good to merge that first.

**Comment by waydegg** [comment]
Made a draft PR for this here #79! Will be waiting for #59 to be merged since the auto completions for commands and for code syntax share the same python object for `prompt_toolkit` sessions.
