### ISSUE TITLE
Cancel openai completion to save tokens

### ISSUE THREAD

**Issue by granawkins** [biobootloader/mentat#80]
When you interrupt the streaming output model, the [stream itself](https://github.com/biobootloader/mentat/blob/3374c7bb723435e426f818273f3a21dde3675bc3/mentat/llm_api.py#L46) doesn't get closed, so I think it still generates (and charges you for) the full response. This [this thread](https://community.openai.com/t/interrupting-completion-stream-in-python/30628/7) shows how to do it, should be simple to integrate.

**Comment by biobootloader** [comment]
😱  Nice catch!!
