### ISSUE TITLE
add an option to run Mentat on a the diff between two commits or branches

### ISSUE THREAD

**Issue by biobootloader** [biobootloader/mentat#81]
Currently, Mentat is aware of uncommitted changes to files in context (the git diff for these files).

It'd be nice if you could make it aware of changes that have been committed. Like have it look at the changes from the last 3 commit, or the difference between two branches (a PR review assistant?). This could make it more helpful at continuing changes you are working on, or helping you review a PR.

This could also be a way to automatically give context - instead of manually choosing files, just look at all the files that have changes.

**Comment by granawkins** [comment]
I can take a go at this. I'm thinking 3 new (optional) arguments:

1. `--history -h *int`: Include the diffs of last-n commits
2. `--commits -c *hash`: List of specific commits
3. `--branches -b *branch_name`: List of specific branches

- Diffs are split up and appended to the files for the prompt (like the current git diff)
- If you pass a `paths` arg, it includes diffs for only those paths. `--exclude-paths` applies.
- If you don't pass a `paths` arg, by default it includes all files referenced by diffs

Most of this takes place inside `CodeFileManager` and a new class, `CodeDiff` (representing one commit- or branch-diff).

So for your examples above:
- Changes from last 3 commits: `mentat -h 3`
- Difference between 2 branches: `mentat -b other-branch`
- Look at all files that have changed in a commit: `mentat -c commit-hash`
- (bonus) Recent activity on a particular file: `mentat myfile.py -h 5`

**Comment by granawkins** [comment]
Done for now with #86
